version: '3'
services:
  stock-market-rest-service:
    image: ghcr.io/voityvaiti/stock-market-rest-service:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - SERVER_PORT = 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_market_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty123
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/stock_market

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: stock_market_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.runCommand({ ping: 1 })'" ]
      interval: 10s
      timeout: 5s
      retries: 5