version: '3'
services:
  stock-market-rest-service:
    image: ghcr.io/voityvaiti/stock-market-rest-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT = 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock_market_db
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/your_database_name

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: stock_market_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"